struct Building {
    name: string,
    icon: image,
}

struct Chunk {
    building: Building,
}

export component ChunkView inherits Rectangle {
    in-out property <bool> has_building;
    in-out property <Chunk> chunk;

    if has_building : Text {
        text: chunk.building.name;
    }
}

export component Map {
    in-out property <int> w;
    in-out property <int> h;
    in-out property <[Chunk]> chunks;
}

export component HelloWorld inherits Window {
    width: 400px;
    height: 400px;

    // Declare an alias that exposes the label's text property to C++
    in property my_label <=> label.text;

    label := Text {
       y: parent.width / 2;
       x: parent.x + 200px;
       text: "Hello, world";
       color: blue;
    }
}